#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the navbar)
name: Juan Jose Solorzano

# Your site's title (e.g., Ben's Awesome Site, The GitHub Blog, etc.), used as part of the title tag like Home | Ben's Awesome Site.
title: Juan Jose Solorzano

# Link to avatar in the navbar (/assets/images/avatar.png). Leave empty if no logo desired. Two avatars for light and dark mode.
# Avatar for light mode site
lightavatar: /assets/images/topIcon2.png
# Avatar for dark mode site
darkavatar: /assets/images/topIcon2.png

# A short description (e.g., A blog dedicated to reviewing cat gifs), used as part of the title tag like Ben's Awesome Site | A blog dedicated to reviewing cat gifs instead of Ben's Awesome Site | Long description about a blog dedicated to reviewing cat gifs that would be used when page.title is not defined.
tagline: Blog dedicated to sharing knowledge and insights in engineering and computer science.

# A longer description used for the description meta tag. Also used as fallback for pages that don't provide their own description, and also as part of the page's title tag if neither page.title nor site.tagline has been defined.
description: A blog where I share my knowledge and insights in engineering and computer science, covering topics such as programming, web development, data science, and more.

# The full URL to your site. Note: site.github.url will be used by default.
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# global author information
author: Juan Jose Solorzano

# URL to a site-wide logo (e.g., /assets/your-company-logo.png)
logo: /assets/images/topIcon.png  

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

permalink: /:year/:month/:day/:title/

collections:
  pages:
    output: true

# Includes an icon in the footer for each username you enter
footer-links:
  email: juanjose.solorzano.c@gmail.com
  facebook:
  github: JuanJoseSolorzano
  instagram: 
  linkedin: juanjosesolorzano
  rss: # just type anything here for a working RSS icon
  twitter: 
  cv: "https://drive.google.com/file/d/1wFHA2r4rMNUMObuBY7JwMah547orm6ET/view?usp=drive_link"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
